name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
  
  windows-test:
    runs-on: windows-latest
    env:
      OPENSSL_DIR: C:\Program Files\OpenSSL-Win64 
    steps:
      - name: Run tests
        run: cargo test --verbose
