name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      if: matrix.os == 'windows-latest'
      run: |
        set OPENSSL_DIR=C:\Program Files\OpenSSL-Win64
        cargo test --verbose
    - name: Run tests
      if: matrix.os != 'windows-latest'
      run: cargo test --verbose
